<script type="text/javascript">

	if ("undefined" !== typeof jQuery)
	{
		var P = (function($)
		{
			return {
				save: function(element)
				{
					var target = $(element).data('target');

					/**
					 * Send AJAX request
					 */
					$.post(target, $(element).parents('form:first').serialize(), function(response)
					{
						if (response.success)
						{
							if ('undefined' !== typeof customer_price_gridJsObject)
							{
								customer_price_gridJsObject.reload();
							}

							return true;
						}
						else 
						{
							alert(response.error);
						}
					}, 'json');
					
					return false;
				},
				apply: function()
				{
					return this;
				}
			}
		})(jQuery).apply();
	}
	else 
	{
		var P = (function()
		{
			return {
				save: function()
				{
					alert('<?php echo __('Requires jQuery 1.11+') ?>');
					
					return false;
				}
			}
		})();
	}
</script>
<div class="field with-note">
	<label class="label"></label>
	<button type="button" onclick="return P.save(this)" data-target="<?php echo $this->getTarget() ?>" class="action-default scalable action-secondary">Create</button>
</div>
